---
development:
  cloud_name: homes4queers
  api_key: '347644226633774'
  api_secret: K7JaXL1GblOoiJNmZz-qNga5Sd0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: homes4queers
  api_key: '347644226633774'
  api_secret: K7JaXL1GblOoiJNmZz-qNga5Sd0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: homes4queers
  api_key: '347644226633774'
  api_secret: K7JaXL1GblOoiJNmZz-qNga5Sd0
  enhance_image_tag: true
  static_image_support: false
