require "administrate/base_dashboard"

class ListingDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    user: Field::BelongsTo,
    comments: Field::HasMany,
    flags: Field::HasMany,
    images: Field::HasMany,
    id: Field::Number,
    name: Field::String,
    description: Field::Text,
    location: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    latitude: Field::Number.with_options(decimals: 2),
    longitude: Field::Number.with_options(decimals: 2),
    bedrooms: Field::Number,
    rent_date: Field::DateTime,
    price: Field::Number,
    basement: Field::Boolean,
    sublet: Field::Boolean,
    utilities_included: Field::Boolean,
    space_type: Field::String,
    current_roommates: Field::Number,
    wheelchair_accessible: Field::Boolean,
    visually_accessible: Field::Boolean,
    hearing_accessible: Field::Boolean,
    assistance_animal: Field::Boolean,
    fridge: Field::Boolean,
    stove: Field::Boolean,
    dishwasher: Field::Boolean,
    microwave: Field::Boolean,
    bathtub: Field::Boolean,
    fireplace: Field::Boolean,
    ac: Field::Boolean,
    electric_heat: Field::Boolean,
    forced_air_heat: Field::Boolean,
    boiler_system: Field::Boolean,
    cats: Field::Boolean,
    dogs: Field::Boolean,
    small_pets: Field::Boolean,
    ensuite_laundry: Field::Boolean,
    shared_laundry: Field::Boolean,
    coinop_laundry: Field::Boolean,
    balcony: Field::Boolean,
    deck: Field::Boolean,
    yard_shared: Field::Boolean,
    yard_private: Field::Boolean,
    pool: Field::Boolean,
    exercise_room: Field::Boolean,
    party_room: Field::Boolean,
    furnished: Field::Boolean,
    parking: Field::Boolean,
    on_street_parking: Field::Boolean,
    smoking: Field::Boolean,
    flagged: Field::Boolean,
  }

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :user,
    :comments,
    :flags,
    :images,
  ]

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = [
    :user,
    :comments,
    :flags,
    :images,
    :id,
    :name,
    :description,
    :location,
    :created_at,
    :updated_at,
    :latitude,
    :longitude,
    :bedrooms,
    :rent_date,
    :price,
    :basement,
    :sublet,
    :utilities_included,
    :space_type,
    :current_roommates,
    :wheelchair_accessible,
    :visually_accessible,
    :hearing_accessible,
    :assistance_animal,
    :fridge,
    :stove,
    :dishwasher,
    :microwave,
    :bathtub,
    :fireplace,
    :ac,
    :electric_heat,
    :forced_air_heat,
    :boiler_system,
    :cats,
    :dogs,
    :small_pets,
    :ensuite_laundry,
    :shared_laundry,
    :coinop_laundry,
    :balcony,
    :deck,
    :yard_shared,
    :yard_private,
    :pool,
    :exercise_room,
    :party_room,
    :furnished,
    :parking,
    :on_street_parking,
    :smoking,
    :flagged,
  ]

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :user,
    :comments,
    :flags,
    :images,
    :name,
    :description,
    :location,
    :latitude,
    :longitude,
    :bedrooms,
    :rent_date,
    :price,
    :basement,
    :sublet,
    :utilities_included,
    :space_type,
    :current_roommates,
    :wheelchair_accessible,
    :visually_accessible,
    :hearing_accessible,
    :assistance_animal,
    :fridge,
    :stove,
    :dishwasher,
    :microwave,
    :bathtub,
    :fireplace,
    :ac,
    :electric_heat,
    :forced_air_heat,
    :boiler_system,
    :cats,
    :dogs,
    :small_pets,
    :ensuite_laundry,
    :shared_laundry,
    :coinop_laundry,
    :balcony,
    :deck,
    :yard_shared,
    :yard_private,
    :pool,
    :exercise_room,
    :party_room,
    :furnished,
    :parking,
    :on_street_parking,
    :smoking,
    :flagged,
  ]

  # Overwrite this method to customize how listings are displayed
  # across all pages of the admin dashboard.
  #
  # def display_resource(listing)
  #   "Listing ##{listing.id}"
  # end
end
